#!/usr/bin/env bash
# Fetch Boost HEADERS and write a tiny CMake config shim, so building Bitcoin
# Core's kernel library does not depend on the distro's Boost.
#
# Core's CMake requires Boost >= 1.74 unconditionally, but only ever links the
# header-only Boost::headers target. Distros differ (manylinux_2_28 ships 1.66,
# too old), so releases fetch a known version instead. Nothing is compiled.
#
#   scripts/fetch_boost_headers.sh [DEST]      # default: build/deps
#   then build with:  -Ccmake.define.Boost_DIR=<DEST>/boost-shim
#                 or: CMAKE_ARGS="-DBoost_DIR=<DEST>/boost-shim"
set -euo pipefail

BOOST_VERSION="${BOOST_VERSION:-1.86.0}"
DEST="${1:-build/deps}"
UNDERSCORED="${BOOST_VERSION//./_}"
URL="https://archives.boost.io/release/${BOOST_VERSION}/source/boost_${UNDERSCORED}.tar.gz"

mkdir -p "$DEST"
DEST="$(cd "$DEST" && pwd)"

if [ ! -f "$DEST/boost_${UNDERSCORED}/boost/version.hpp" ]; then
  echo "fetching Boost ${BOOST_VERSION} headers" >&2
  curl -fsSL --retry 3 "$URL" | tar -xz -C "$DEST" "boost_${UNDERSCORED}/boost"
fi

SHIM="$DEST/boost-shim"
mkdir -p "$SHIM"
cat > "$SHIM/BoostConfig.cmake" <<CMAKE
# Generated by scripts/fetch_boost_headers.sh - do not edit.
set(Boost_INCLUDE_DIR "$DEST/boost_${UNDERSCORED}")
if(NOT TARGET Boost::headers)
  add_library(Boost::headers INTERFACE IMPORTED)
  set_target_properties(Boost::headers PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "\${Boost_INCLUDE_DIR}")
endif()
set(Boost_FOUND TRUE)
CMAKE
cat > "$SHIM/BoostConfigVersion.cmake" <<CMAKE
set(PACKAGE_VERSION "${BOOST_VERSION}")
if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
  set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
endif()
CMAKE

echo "$SHIM"
